/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

export function Galaxymodel(props: any) {
  const { nodes, materials } = useGLTF("/need_some_space.glb");
  return (
    <group {...props} dispose={null}>
      <points
        // geometry={nodes.Object_2.geometry}
        geometry={(nodes.Object_2 as THREE.Mesh).geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.013}
      />
    </group>
  );
}

useGLTF.preload("/need_some_space.glb");
